import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { CheckCircle2, Layers, Loader2, FileText, ListChecks } from "lucide-react";
import Modal from "./Modal";
import { createJob } from "../services/api";
import { useJobs } from "../context/JobsContext";
import { cn } from "../lib/format";

const BULK_SIZES = [10, 25, 50, 100];

const inputClass =
  "w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none transition focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100 dark:border-slate-700 dark:bg-slate-800 dark:text-white dark:focus:border-indigo-500 dark:focus:ring-indigo-500/20";

export default function BulkJobModal({ open, onClose }) {
  const navigate = useNavigate();
  const { refresh } = useJobs();

  const [count, setCount] = useState(25);
  const [kind, setKind] = useState("default");
  const [progress, setProgress] = useState(null);
  const [done, setDone] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (open) {
      setCount(25);
      setKind("default");
      setProgress(null);
      setDone(null);
      setError(null);
    }
  }, [open]);

  async function handleSubmit() {
    if (progress) return;
    setError(null);
    setProgress({ queued: 0, total: count });
    try {
      for (let i = 0; i < count; i += 1) {
        const payload =
          kind === "generate-pdf"
            ? {
                title: "Bulk generated report",
                content: `Bulk job ${i + 1} of ${count}\nGenerated by the queue demo.`,
              }
            : { name: `Bulk job ${i + 1} of ${count}` };
        await createJob(kind, payload, "normal");
        setProgress((p) => ({ ...p, queued: i + 1 }));
      }
      setDone(count);
      refresh();
    } catch (err) {
      setError(err?.response?.data?.error || err.message || "Failed to queue bulk jobs");
    } finally {
      setProgress(null);
    }
  }

  const percent = progress
    ? Math.round((progress.queued / progress.total) * 100)
    : 0;

  const secondary =
    "text-slate-600 hover:bg-slate-50 dark:text-slate-300 dark:hover:bg-slate-800";

  return (
    <Modal
      open={open}
      onClose={onClose}
      title="Bulk Job Demo"
      subtitle="Add multiple real jobs to the queue at once"
    >
      {done ? (
        <div className="flex flex-col items-center py-6 text-center">
          <span className="flex h-14 w-14 items-center justify-center rounded-full bg-emerald-100 text-emerald-600 dark:bg-emerald-500/15 dark:text-emerald-400">
            <CheckCircle2 size={28} />
          </span>
          <h3 className="mt-4 text-lg font-semibold text-slate-900 dark:text-white">
            {done} jobs queued
          </h3>
          <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
            The worker is processing them now — watch the dashboard update as
            the queue drains.
          </p>
          <div className="mt-6 flex w-full max-w-xs gap-3">
            <button
              onClick={() => navigate("/jobs")}
              className="flex-1 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-500"
            >
              View Jobs
            </button>
            <button
              onClick={onClose}
              className={cn("flex-1 rounded-lg border border-slate-200 px-4 py-2 text-sm font-medium dark:border-slate-700", secondary)}
            >
              Close
            </button>
          </div>
        </div>
      ) : (
        <div className="space-y-5">
          <p className="text-sm text-slate-500 dark:text-slate-400">
            Each job is individually added to the BullMQ queue through{" "}
            <code className="rounded bg-slate-100 px-1 py-0.5 text-xs dark:bg-slate-800">POST /jobs</code>{" "}
            and processed by the worker.
          </p>

          <div>
            <p className="mb-2 text-sm font-medium text-slate-700 dark:text-slate-300">
              Number of jobs
            </p>
            <div className="flex flex-wrap gap-2">
              {BULK_SIZES.map((n) => (
                <button
                  key={n}
                  onClick={() => setCount(n)}
                  className={cn(
                    "min-w-16 rounded-lg border px-4 py-2 text-sm font-medium transition",
                    count === n
                      ? "border-indigo-500 bg-indigo-50 text-indigo-700 dark:border-indigo-500 dark:bg-indigo-500/15 dark:text-indigo-300"
                      : "border-slate-200 text-slate-600 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800"
                  )}
                >
                  {n}
                </button>
              ))}
            </div>
          </div>

          <div>
            <p className="mb-2 text-sm font-medium text-slate-700 dark:text-slate-300">
              Job type
            </p>
            <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
              {[
                { id: "default", icon: ListChecks, label: "Background Jobs", desc: "Fast, ~3s each" },
                { id: "generate-pdf", icon: FileText, label: "PDF Reports", desc: "Writes a real PDF each" },
              ].map((opt) => {
                const Icon = opt.icon;
                return (
                  <button
                    key={opt.id}
                    onClick={() => setKind(opt.id)}
                    className={cn(
                      "flex items-center gap-3 rounded-xl border p-3 text-left transition",
                      kind === opt.id
                        ? "border-indigo-500 bg-indigo-50 dark:border-indigo-500 dark:bg-indigo-500/10"
                        : "border-slate-200 hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800"
                    )}
                  >
                    <Icon size={18} className={kind === opt.id ? "text-indigo-600 dark:text-indigo-400" : "text-slate-400"} />
                    <div>
                      <p className="text-sm font-medium text-slate-900 dark:text-white">{opt.label}</p>
                      <p className="text-xs text-slate-500 dark:text-slate-400">{opt.desc}</p>
                    </div>
                  </button>
                );
              })}
            </div>
          </div>

          {progress && (
            <div>
              <div className="mb-1.5 flex items-center justify-between text-xs text-slate-500 dark:text-slate-400">
                <span className="inline-flex items-center gap-1.5">
                  <Loader2 size={13} className="animate-spin" />
                  Queueing {progress.queued}/{progress.total}
                </span>
                <span>{percent}%</span>
              </div>
              <div className="h-2 w-full overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800">
                <div
                  className="h-full rounded-full bg-indigo-500 transition-all duration-200"
                  style={{ width: `${percent}%` }}
                />
              </div>
            </div>
          )}

          {error && (
            <div className="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:border-rose-500/30 dark:bg-rose-500/10 dark:text-rose-300">
              {error}
            </div>
          )}

          <div className="flex items-center justify-between border-t border-slate-100 pt-4 dark:border-slate-800">
            <span className="inline-flex items-center gap-1.5 text-xs text-slate-400 dark:text-slate-500">
              <Layers size={13} />
              Will enqueue via the live queue
            </span>
            <button
              onClick={handleSubmit}
              disabled={!!progress}
              className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white transition hover:bg-indigo-500 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {progress && <Loader2 size={15} className="animate-spin" />}
              Add Jobs to Queue
            </button>
          </div>
        </div>
      )}
    </Modal>
  );
}